# Generated by Django 2.2.19 on 2022-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-always_top', '-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='group',
            name='admins_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='always_top',
            field=models.BooleanField(default=False),
        ),
    ]
